### ISSUE TITLE
Support SMTP

### ISSUE THREAD

**Issue by tonsV2** [ainsleyclark/go-mail#1]
It would be great if plain old SMTP was supported.

For development, and for apps which only sends a few mails, I often use Gmail's SMTP or other SMTP servers.

**Comment by ainsleyclark** [comment]
HI @tonsV2 we will get the sorted.

**Comment by ainsleyclark** [comment]
Hi @tonsV2 

A very basic implementation of SMTP has been released: 550fe61

Note, it doesn't support TLS yet.

Hope this helps!
