### ISSUE TITLE
Changes in v1.1.x break any project that imports v1.0.x

### ISSUE THREAD

**Issue by tsawler** [ainsleyclark/go-mail#19]
Hi:

I don't suppose that you could move v1.1.x to a v2 branch; any project that uses this package and wrote code as required in v1.0.x now breaks when go get -u is executed, since you've moved to the (much better) approach that you have in version 1.1.x. 

Obviously, this is not a huge deal, but it would make life easier for those of us who are using your package, and it also is a more correct approach of versioning, since v1.1.x introduces breaking changes.

This is just a suggestion, of course.

Thanks again for this useful package.

**Comment by ainsleyclark** [comment]
Hi @tsawler 

Thank you for your feedback and suggestions, and using the package!

This is a very good point. I should have included breaking changes in the change log but as I thought as the project is still quite young, it wouldn't matter so much.

For the time being I will add a chagelog in the readme, and the next update I do I will move to V2. If that's ok with you? 

As I have moved the drivers to a different package, I can't forsee any breaking changes in a very long time.

Again, thank you for the feedback.

**Comment by tsawler** [comment]
It works for me. I actually used this package for one of my Golang based Udemy courses, and I’ll have to re-record one lecture, but that’s no big deal.

Take care.

—
Trevor Sawler

**Comment by ainsleyclark** [comment]
@tsawler wow that's fantastic! Can you share the course by any chance?

**Comment by tsawler** [comment]
Sure. This is the link:

[Let's build a Go version of Laravel](https://www.udemy.com/course/lets-build-a-go-version-of-laravel/?referralCode=96DECD8BA7FEE1726C8A)
