### ISSUE TITLE
Postal Support

### ISSUE THREAD

**Issue by Bene-GG** [ainsleyclark/go-mail#6]
### Description
"Postal is a complete and fully featured mail server for use by websites & web servers. Think Sendgrid, Mailgun or Postmark but open source and ready for you to run on your own servers."

Repo: [https://github.com/postalserver/postal](https://github.com/postalserver/postal)
API docs: [https://docs.postalserver.io/developer/api](https://docs.postalserver.io/developer/api)

**Comment by ainsleyclark** [comment]
Thanks @Bene-GG 

I'll add this soon!

**Comment by ainsleyclark** [comment]
Hi @Bene-GG 

I have added Postal support, you may need to run the following before testing it out.

```go get github.com/ainsleyclark.go-mail@7e88576869b79a83b745c728a6b2e3db08cd3cb4```

Let me know if everything works!

All the best.
